kafka:
  clusters:
    -
      id: wrYGf-csNgiGdK7B_ADF7Z
      name: local
      bootstrapServers: kafka0:29092
      jmxHost: kafka0
      jmxPort: 9997
      zookeeper: zookeeper0:2181
    -
      id: dMMQx-WRh77BKYas_g2ZTz
      name: secondLocal
      bootstrapServers: kafka1:29092
      jmxHost: kafka1
      jmxPort: 9997
      zookeeper: zookeeper1:2181