kafka:
  clusters:
    -
      name: local
      bootstrapServers: kafka0:29092
      zookeeper: zookeeper0:2181
    -
      name: secondLocal
      zookeeper: zookeeper1:2181
      bootstrapServers: kafka1:29092