kafka:
  clusters:
    -
      name: local
      bootstrapServers: localhost:29091
      zookeeper: localhost:2181
    -
      name: secondLocal
      bootstrapServers: localhost:29092
      zookeeper: localhost:2182